// @generated by scripts/gen-formats.cjs — DO NOT EDIT
// 数据来源：packages/app/src/lib/formats/formats.json（前端 lib/formats/formats.ts 亦消费同一份）。
// 修改格式清单请改 formats.json 后运行 pnpm gen:formats。

/// 受支持的图片扩展名（小写，不含点）。用于目录列举与启动参数识别。
/// - jpe/jfif 是 JPEG 别名、hif 是 HEIF 容器，分别沿用 JPEG/HEIC 的解码通道；
/// - svg 交给 WebView 渲染；
/// - tga/pbm/pgm/ppm/pnm/dds/hdr/exr/qoi 由 image crate 解码（默认 feature 已带）。
pub const SUPPORTED_EXT: &[&str] = &[
    "jpg",
    "jpeg",
    "jpe",
    "jfif",
    "png",
    "gif",
    "webp",
    "bmp",
    "ico",
    "svg",
    "tiff",
    "tif",
    "avif",
    "heic",
    "heif",
    "hif",
    "tga",
    "pbm",
    "pgm",
    "ppm",
    "pnm",
    "dds",
    "hdr",
    "exr",
    "qoi",
];

/// 可直接改写原图的扩展名（heic 无编码器、svg 矢量、gif 动图会丢帧）→ 保存格式名。
pub fn editable_ext_format(ext: &str) -> Option<&'static str> {
    match ext {
        "jpg" => Some("jpeg"),
        "jpeg" => Some("jpeg"),
        "jpe" => Some("jpeg"),
        "jfif" => Some("jpeg"),
        "png" => Some("png"),
        "webp" => Some("webp"),
        "bmp" => Some("bmp"),
        "tiff" => Some("tiff"),
        "tif" => Some("tiff"),
        "avif" => Some("avif"),
        "tga" => Some("tga"),
        "qoi" => Some("qoi"),
        "exr" => Some("exr"),
        _ => None,
    }
}
