#!/usr/bin/env node
/**
 * 格式清单生成器：从 packages/app/src/lib/formats.json（单一事实来源）生成
 *   1. packages/app/src-tauri/src/formats_gen.rs —— SUPPORTED_EXT 常量 + 可编辑扩展名→格式表
 *   2. 重写 packages/app/src-tauri/tauri.conf.json 的 bundle.fileAssociations 字段
 *
 * 生成物提交入库（beforeBuildCommand 不挂本脚本）。修改 formats.json 后必须运行：
 *   pnpm gen:formats
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const JSON_PATH = path.join(ROOT, 'packages', 'app', 'src', 'lib', 'formats.json');
const RS_PATH = path.join(ROOT, 'packages', 'app', 'src-tauri', 'src', 'formats_gen.rs');
const CONF_PATH = path.join(ROOT, 'packages', 'app', 'src-tauri', 'tauri.conf.json');

const formats = JSON.parse(fs.readFileSync(JSON_PATH, 'utf8'));

// ---------- 1. formats_gen.rs ----------

// 可编辑扩展名 → 保存格式（对应 Rust save_edits 里的 match；jpe/jfif/tif 是别名）
const ALIAS = { jpg: 'jpeg', jpeg: 'jpeg', jpe: 'jpeg', jfif: 'jpeg', tif: 'tiff' };
const editablePairs = formats.editable.map((ext) => [ext, ALIAS[ext] ?? ext]);

const rs = `// @generated by scripts/gen-formats.cjs — DO NOT EDIT
// 数据来源：packages/app/src/lib/formats.json（前端 lib/formats.ts 亦消费同一份）。
// 修改格式清单请改 formats.json 后运行 pnpm gen:formats。

/// 受支持的图片扩展名（小写，不含点）。用于目录列举与启动参数识别。
/// - jpe/jfif 是 JPEG 别名、hif 是 HEIF 容器，分别沿用 JPEG/HEIC 的解码通道；
/// - svg 交给 WebView 渲染；
/// - tga/pbm/pgm/ppm/pnm/dds/hdr/exr/qoi 由 image crate 解码（默认 feature 已带）。
pub const SUPPORTED_EXT: &[&str] = &[
${formats.supported.map((e) => `    "${e}",`).join('\n')}
];

/// 可直接改写原图的扩展名（heic 无编码器、svg 矢量、gif 动图会丢帧）→ 保存格式名。
pub fn editable_ext_format(ext: &str) -> Option<&'static str> {
    match ext {
${editablePairs.map(([ext, fmt]) => `        "${ext}" => Some("${fmt}"),`).join('\n')}
        _ => None,
    }
}
`;

fs.writeFileSync(RS_PATH, rs);

// ---------- 2. tauri.conf.json 的 fileAssociations ----------

// 深拷贝一份配置、替换 fileAssociations，其余字段原样保留；2 空格缩进写回
const conf = JSON.parse(fs.readFileSync(CONF_PATH, 'utf8'));
conf.bundle.fileAssociations = formats.fileAssociations.map(({ ext, name, description, role, contentTypes, mimeType }) => {
  const assoc = { ext, name, description, role };
  if (contentTypes) assoc.contentTypes = contentTypes;
  if (mimeType) assoc.mimeType = mimeType;
  return assoc;
});
fs.writeFileSync(CONF_PATH, JSON.stringify(conf, null, 2) + '\n');

console.log(`✓ 已生成 ${path.relative(ROOT, RS_PATH)}`);
console.log(`✓ 已更新 ${path.relative(ROOT, CONF_PATH)} 的 fileAssociations（${conf.bundle.fileAssociations.length} 组）`);
